name = "osm-changeset-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "osm-changesets"
database_id = "cea39bd5-5b71-4ffa-bf9f-09333cf2eef5"

[triggers]
crons = ["* * * * *"]

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true